services:
  - type: web
    name: unit
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 300 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PIN
        value: 8798
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
      - key: TEXTBELT_KEY
        value: 1e75c135dcdcffe0d5d988a6f94a8c493f4c5e2fE4HPIiQ70HFrxcFHSXXy5RRgZ
    disk:
      name: unit-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
